services:

  globalyhub_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: globalyhub_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - globalyhub_postgres
      - globalyhub_redis
    networks:
      - laravel_net

  globalyhub_webserver:
    image: nginx:alpine
    container_name: globalyhub_webserver
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - globalyhub_app
    networks:
      - laravel_net

  globalyhub_postgres:
    image: postgres:16
    container_name: globalyhub_postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_net

  globalyhub_redis:
    image: redis:7-alpine
    container_name: globalyhub_redis
    networks:
      - laravel_net

  globalyhub_queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: globalyhub_queue
    working_dir: /var/www
    command: php artisan queue:work --tries=5 --sleep=3
    volumes:
      - .:/var/www
    depends_on:
      - globalyhub_redis
      - globalyhub_postgres
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  pgdata:
